# Generated by Django 6.0.3 on 2026-03-13 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ipl_batting_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='ipl_bowling_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='ipl_economy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='ipl_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='ipl_runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='ipl_strike_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='ipl_wickets',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PlayerMatchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balls_faced', models.IntegerField(default=0)),
                ('runs_scored', models.IntegerField(default=0)),
                ('dismissals', models.IntegerField(default=0)),
                ('strike_rate', models.FloatField(default=0.0)),
                ('batsman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchups_as_batsman', to='api.player')),
                ('bowler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchups_as_bowler', to='api.player')),
            ],
            options={
                'unique_together': {('batsman', 'bowler')},
            },
        ),
    ]
