# Generated by Django 6.0.3 on 2026-03-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_player_ipl_batting_avg_player_ipl_bowling_avg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bowling_style',
            field=models.CharField(choices=[('Pace', 'Pace'), ('Spin', 'Spin'), ('None', 'None')], default='Pace', max_length=50),
        ),
    ]
