# Generated by Django 6.0.3 on 2026-03-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_player_bowling_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bowling_style',
            field=models.CharField(choices=[('Swing Specialist', 'Swing Specialist'), ('Death Specialist', 'Death Specialist'), ('Spinner', 'Spinner'), ('All-Round Pacer', 'All-Round Pacer'), ('All-Round Spinner', 'All-Round Spinner'), ('None', 'None')], default='None', max_length=50),
        ),
    ]
