# Generated by Django 6.0.3 on 2026-03-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_player_bowling_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='star_rating',
            field=models.FloatField(default=2.5),
        ),
    ]
