# Generated by Django 6.0.3 on 2026-03-14 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_player_star_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='dew_factor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='home_advantage_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_matches', to='api.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='pitch_type',
            field=models.CharField(choices=[('Batting', 'Batting'), ('Spin', 'Spin'), ('Pace', 'Pace'), ('Balanced', 'Balanced')], default='Balanced', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='batting_consistency',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='player',
            name='batting_power',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='player',
            name='death_bowling_skill',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='player',
            name='fielding_skill',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='player',
            name='is_spinner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='middle_overs_skill',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='player',
            name='pace_skill',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='player',
            name='powerplay_skill',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='player',
            name='spin_skill',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='player',
            name='tactical_role',
            field=models.CharField(choices=[('Anchor', 'Anchor'), ('Finisher', 'Finisher'), ('Power Hitter', 'Power Hitter'), ('Standard', 'Standard')], default='Standard', max_length=50),
        ),
    ]
