# Generated by Django 6.0.3 on 2026-03-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_match_dew_factor_match_home_advantage_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('Batsman', 'Batsman'), ('Bowler', 'Bowler'), ('All-rounder', 'All-rounder'), ('Batting All-rounder', 'Batting All-rounder'), ('Bowling All-rounder', 'Bowling All-rounder'), ('Wicketkeeper', 'Wicketkeeper')], max_length=50),
        ),
    ]
